#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include "llama.h"
#include <string>
#include <vector>
#include <map>
#include <cstdint>

// Fast file fingerprint (mtime:size) for cache validation without reading content.
std::string file_fingerprint(const std::string& path);

// Write a save file with a one-line text header containing the git SHA,
// followed by the raw llama state.  The header format is:
//     LLLM_SAVE_v1 git_sha=<40-hex>\n<raw-state-bytes>
// Returns true on success.  Overwrites any existing file at save_path.
bool write_llm_save(const std::string& save_path, const uint8_t* state_data, size_t state_size);

// Read the header from an LLLM save file.
// On success returns the git SHA and sets *header_size to the byte count of
// the header line (including trailing newline).  The raw llama state begins
// at offset *header_size in the file.  Returns "" for unrecognized / old-style
// files (callers should fall back to llama_state_load_file directly).
std::string read_llm_save_header(const std::string& save_path, size_t* header_size);

// --- Compact token-based save/restore ---
// Save format: LLLM_SAVE_V2 git_sha=<40-hex> n_tokens=<N>\n<token_ids_as_int32_le>
// Only stores the token sequence; on restore the KV cache is regenerated by
// re-decoding all tokens through the model.  For a 75K-token session this is
// ~300 KB instead of ~2 GB (raw KV cache).
bool write_token_save(const std::string& save_path, const std::vector<llama_token>& tokens);
bool read_token_save(const std::string& save_path, std::vector<llama_token>& tokens);

// V1 cache: after a slow V2 restore, auto-save the rebuilt KV cache for instant
// future restores.  Cache lives in <cwd>/.cache/<hash>.
bool try_load_v1_cache(const std::string& v2_path, const std::string& model_path,
                       const std::string& git_sha, struct llama_context* ctx);
// After a successful V2 restore, persist the current KV cache as a V1 cache entry.
// Returns true on success.
bool write_v1_cache(const std::string& v2_path, const std::string& model_path,
                    const std::string& git_sha, struct llama_context* ctx);
std::string get_cache_dir();
#include <functional>

class FileSystemTools {
public:
  FileSystemTools();

  // Execute a shell command. Callbacks fire as output arrives, allowing
  // real-time streaming. on_open is called once before any output, on_chunk
  // per read(), and on_close after the command finishes (with the full result).
  std::string exec_shell(const std::string& command,
                         std::function<void()> on_open = nullptr,
                         std::function<void(const std::string&)> on_chunk = nullptr,
                         std::function<void(const std::string&)> on_close = nullptr);

  std::vector<std::map<std::string, std::string>> read_files(const std::vector<std::string>& paths);

  std::map<std::string, std::string> write_file(const std::string& path, const std::string& content);

  std::map<std::string, std::string> edit_file(const std::string& path, const std::string& old_str, const std::string& new_str);

  // Search for text with optional line range.
  // Returns map with keys: "content" (LLM-facing result), "match_count",
  // "actual_start", "actual_end" (for line-range mode), "error" (non-empty on failure).
  std::map<std::string, std::string> search_file(const std::string& path, const std::string& text, const std::string& begin_str = "", const std::string& end_str = "");

private:
  std::string _get_fullpath(const std::string& path);
};

// --- Consolidated Diagnostic Logging Function ---
// This function handles all diagnostic output to both session and log file
// Parameters:
//   - message: The diagnostic message to output
//   - logOnly: If true, only write to log file (not to session)
//   - debugOnly: If true, only output when LLLM_DEBUG=1 environment variable is set
//   - tag: Optional tag to prepend to the message (e.g., "[Edit]")
void log_diagnostic(const std::string& message, bool logOnly = false, bool debugOnly = false,
                    const std::string& tag = "");

// Styled wrapper: outputs tool call diagnostics with .tool-label colors in the browser.
// Writes to chat_log, styled HTML to browser pipe, and plain text to stdout.
void log_tool_diagnostic(const std::string& message, bool debugOnly = false,
                         const std::string& tag = "");



// Global debug flag - declared in main.cc and used by other modules
extern bool is_debug;

// Chat log file stream - declared in main.cc and used for all tool diagnostics
extern std::ofstream chat_log;

// Output mode control functions - declared in output.h
#include "output.h"

#endif // FILESYSTEM_H
