#include "llama.h"
#include "common.h"
#include "filesystem.h"
#include "network.h"
#include "tokens.h"
#include "output.h"
#include "signals.h"
#include "server.h"
#include "model.h"
#include "session.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cstdlib>
#include <cstring>
#include <set>
#include <clocale>
#include <ctime>
#include <sys/stat.h>
#include <unistd.h>
#include <pwd.h>

// --- Helper to escape token piece strings for token log ---
static string escape_token_piece(const string& s) {
    string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '\n') out += "\\n";
        else if (c == '\r') out += "\\r";
        else if (c == '\t') out += "\\t";
        else if (c == '"') out += "\\\"";
        else out += c;
    }
    return out;
}

// --- Global State ---
bool is_debug = false;
ofstream chat_log;
ofstream token_log;
string INITIAL_CWD;

static void diag_impl(const string& formatted_line, const string& msg) {
    cout << formatted_line << endl;
    if (chat_log.is_open()) {
        chat_log << "[" << msg << "]" << "\n\n";
        chat_log.flush();
    }
}

void diag(const string& msg, const char* color) {
    diag_impl(string(color) + "[" + msg + "]\033[0m", msg);
}

int main(int argc, char ** argv) {
    setlocale(LC_ALL, "");

    uid_t uid = getuid();
    struct passwd *pw = getpwuid(uid);
    if (pw == nullptr || strcmp(pw->pw_name, "ai") != 0) {
        cerr << "Error: This program must be run as user 'ai'" << endl;
        return 1;
    }

    // HOME is initialized at global scope via g_homeInit

    char cwd[1024];
    if (getcwd(cwd, sizeof(cwd)) != nullptr) {
        ofstream cwd_file(HOME+"/.cwd");
        if (cwd_file.is_open()) {
            cwd_file << cwd << endl;
            cwd_file.close();
        }
        // Save initial directory for clear command to restore
        INITIAL_CWD = cwd;
    }

    umask(0002);
    atexit([]() {
        cout << "\033[0m";  // Reset terminal colors on exit
        NetworkTools::cleanup_services();
        cleanup_lllm_server();
    });

    setup_signals();

    if (argc < 2 || argc > 3) {
        cerr << "Usage: " << argv[0] << " <model_path> [restore_file]" << endl;
        return 1;
    }

    // Check if we are restoring from a save file
    bool restore_from_file = (argc == 3);
    string restore_path;
    if (restore_from_file) {
        restore_path = argv[2];
    }

    // Temperature from LLLM_TEMP environment variable
    float temp = 0.7f;
    bool use_dummy_thought = false;
    {
        const char* env = getenv("LLLM_TEMP");
        if (env != nullptr) {
            temp = atof(env);
        }
        if (temp == 0.0f) {
            use_dummy_thought = true;
        }
    }

    const char* debug_env = getenv("LLLM_DEBUG");
    if (debug_env != nullptr && strcmp(debug_env, "1") == 0) {
        is_debug = true;
    }

    if (!is_debug) {
        llama_log_set(dummy_log_callback, nullptr);
    } else {
        llama_log_set(custom_log_callback, nullptr);
    }

    mkdir("log", 0775);
    int log_index = 1;
    string log_file_name;
    while (true) {
        log_file_name = "log/" + to_string(log_index);
        ifstream check_file(log_file_name.c_str());
        if (!check_file.good()) break;
        log_index++;
    }
    chat_log.open(log_file_name, ios::app);
    if (!chat_log.is_open()) {
        cerr << "Error: Failed to open log file. The directory isn't writeable by user ai." << endl;
        return 1;
    }

    // Open token log file (for LLLM_DEBUG=1)
    string token_log_name = "log/" + to_string(log_index) + ".tokens";
    if (is_debug) {
        token_log.open(token_log_name, ios::trunc);
        if (token_log.is_open()) {
            token_log << "# Token Log - Session #" << log_index << "\n";
            token_log << "# Format: FEED <label> <token_id> \"<escaped_piece>\"   (tokens fed into context)\n";
            token_log << "#         <seq> <token_id> \"<escaped_piece>\"                     (tokens generated by LLM)\n";
            token_log << "# Escaping: \\n = newline, \\r = carriage return, \\t = tab\n";
        }
    }

    // Initialize the fast stream pipe
    init_output_stream();

    // Start lllmServer.py if browser output is enabled
    if (should_output_to_browser()) {
        start_lllm_server_if_needed();
    }

    auto log_entry = [&](const string& role, const string& text) {
        if (chat_log.is_open()) {
            chat_log << "=== " << role << " ===\n" << text << "\n\n";
            chat_log.flush();
        }
    };

    diag("Session #" + to_string(log_index) + " started: type /help to see a list of commands", "\033[35m");
    log_entry("SYSTEM", "Starting LLM Controller Session (#" + to_string(log_index) + ")");

    llama_backend_init();
    llama_numa_init(GGML_NUMA_STRATEGY_DISABLED);

    auto mparams = llama_model_default_params();
    // Allow overriding model params with LLLM_* environment variables
    {
        const char* env;
        if ((env = getenv("LLLM_GPU_LAYERS")) != nullptr) {
            mparams.n_gpu_layers = atoi(env);
        } else {
            mparams.n_gpu_layers = 999;
        }
        if ((env = getenv("LLLM_USE_MMAP")) != nullptr) {
            mparams.use_mmap = atoi(env) != 0;
        } else {
            mparams.use_mmap = false;
        }
        if ((env = getenv("LLLM_USE_MLOCK")) != nullptr) {
            mparams.use_mlock = atoi(env) != 0;
        } else {
            mparams.use_mlock = true;
        }
    }

    llama_model * model = llama_model_load_from_file(argv[1], mparams);
    if (!model) return 1;

    const llama_vocab * vocab = llama_model_get_vocab(model);
    ModelType model_type = detect_model_type(vocab);

    auto cparams = llama_context_default_params();
    // Allow overriding context params with LLLM_* environment variables
    {
        const char* env;
        if ((env = getenv("LLLM_CTX")) != nullptr) {
            cparams.n_ctx = atoi(env);
        } else {
            cparams.n_ctx = 262144;
        }
        if ((env = getenv("LLLM_BATCH")) != nullptr) {
            cparams.n_batch = atoi(env);
        } else {
            cparams.n_batch = 2048;
        }
        if ((env = getenv("LLLM_UBATCH")) != nullptr) {
            cparams.n_ubatch = atoi(env);
        } else {
            cparams.n_ubatch = 512;
        }
        if ((env = getenv("LLLM_THREADS")) != nullptr) {
            cparams.n_threads = atoi(env);
        } else {
            cparams.n_threads = 8;
        }
        if ((env = getenv("LLLM_THREADS_BATCH")) != nullptr) {
            cparams.n_threads_batch = atoi(env);
        } else {
            cparams.n_threads_batch = 8;
        }
    }
    cparams.flash_attn_type = (llama_flash_attn_type)1;
    cparams.offload_kqv = true;
    cparams.type_k = GGML_TYPE_Q8_0;
    cparams.type_v = GGML_TYPE_Q8_0;

    llama_context * ctx = llama_init_from_model(model, cparams);
    if (!ctx) return 1;

    // Always load and tokenize the system prompt.
    // This is needed even during restore so that `system_tokens` holds only the
    // actual system prompt (not the full conversation).  clear_context() uses
    // system_tokens to re-seed the KV cache after a wipe, so it must be correct.
    string system_prompt;

    ifstream prompt_file(HOME+"/prompt");
    if (prompt_file.is_open()) {
        stringstream buffer;
        buffer << prompt_file.rdbuf();
        system_prompt = buffer.str();
        prompt_file.close();
    }

    // Append current working directory and date to system prompt
    {
        char current_cwd[1024];
        if (getcwd(current_cwd, sizeof(current_cwd)) != nullptr) {
            system_prompt += "\n\nCurrent working directory: " + string(current_cwd) + "\n";
        }

        time_t now = time(nullptr);
        struct tm tm_buf;
        if (localtime_r(&now, &tm_buf)) {
            char time_str[64];
            strftime(time_str, sizeof(time_str), "%Y-%m-%d %H:%M:%S %Z", &tm_buf);
            system_prompt += "Current date and time: " + string(time_str) + "\n";
        }
    }

    string formatted_system_prompt = string(Tokens::TURN_START) + "system\n" + system_prompt + Tokens::TURN_END + "\n";
    vector<llama_token> system_tokens = common_tokenize(ctx, formatted_system_prompt, true, true);

    // Sampling parameters
    float top_p = 0.8f;
    int32_t top_k = 20;
    float min_p = 0.0f;
    float penalty_present = 1.5f;
    float penalty_repeat = 1.0f;

    if (use_dummy_thought) {
        top_k = 1;
        top_p = 1.0f;
    }

    llama_sampler_chain_params lparams = llama_sampler_chain_default_params();
    llama_sampler * smpl = llama_sampler_chain_init(lparams);
    llama_sampler_chain_add(smpl, llama_sampler_init_penalties(64, penalty_repeat, 0.0f, penalty_present));
    llama_sampler_chain_add(smpl, llama_sampler_init_top_k(top_k));
    llama_sampler_chain_add(smpl, llama_sampler_init_top_p(top_p, 1));
    llama_sampler_chain_add(smpl, llama_sampler_init_min_p(min_p, 1));
    llama_sampler_chain_add(smpl, llama_sampler_init_temp_ext(temp, 0.0f, 1.0f));
    llama_sampler_chain_add(smpl, llama_sampler_init_dist(LLAMA_DEFAULT_SEED));

    llama_batch batch = llama_batch_init(cparams.n_batch, 0, 1);
    int n_past = 0;

    if (!restore_from_file) {
        // Normal startup: feed system prompt tokens into KV cache
        batch.n_tokens = 0;
        for (size_t i = 0; i < (int)system_tokens.size(); i++) {
            common_batch_add(batch, system_tokens[i], n_past++, {0}, (i == (int)system_tokens.size() - 1));
            if (is_debug && token_log.is_open()) {
                string piece = common_token_to_piece(ctx, system_tokens[i]);
                token_log << "FEED SYSTEM_PROMPT_INIT " << system_tokens[i] << " \"" << escape_token_piece(piece) << "\"\n";
                token_log.flush();
            }
        }

        if (!handle_llama_decode_error(ctx, batch)) return 1;
    } else {
        // Restore from save file: load KV cache and all state via llama_state_load_file.
        // This populates the KV cache directly -- no need to feed/decode tokens ourselves.
        diag("Restoring session from " + restore_path + "...", "\033[35m");
        vector<llama_token> restored_tokens(cparams.n_ctx);
        size_t n_restored = 0;
        bool ok = llama_state_load_file(ctx, restore_path.c_str(),
                                         restored_tokens.data(), restored_tokens.size(), &n_restored);
        if (!ok) {
            cerr << "Error: Failed to restore session from " << restore_path << endl;
            return 1;
        }
        // Use the actual KV cache position, not the saved token count.
        // The saved token count only tracks tokens fed via feed_tokens_impl
        // (system prompt, user messages, tool results), but the KV cache also
        // contains all generated assistant tokens that were fed directly via
        // common_batch_add in TokenGenerator.  Using the stale count causes
        // balloc->init to reject the first post-restore batch because the
        // batch positions don't match the real cache boundary.
        llama_pos actual_max = llama_memory_seq_pos_max(llama_get_memory(ctx), 0);
        n_past = (int)(actual_max + 1);

        // Trim restored_tokens to the actual count returned
        restored_tokens.resize(n_restored);

        diag("Session restored: " + to_string(n_past) + " tokens loaded", "\033[32m");
        log_entry("SYSTEM", "Restored session from " + restore_path);

        // Session state with full conversation history for save/restore tracking.
        // system_tokens remains as the real system prompt only (for clear_context).
        SessionState state;
        state.all_context_tokens = restored_tokens;
        state.log_index = log_index;

        // --- Run the main chat session loop ---
        bool result = run_chat_session(
            ctx, vocab, smpl, batch, n_past, cparams,
            system_tokens, use_dummy_thought,
            state
        );

        // Cleanup
        llama_free(ctx);
        llama_model_free(model);
        llama_backend_free();
        return 0;
    }

    // Session state (normal startup)
    SessionState state;
    state.all_context_tokens = system_tokens;
    state.log_index = log_index;

    // --- Run the main chat session loop ---
    bool result = run_chat_session(
        ctx, vocab, smpl, batch, n_past, cparams,
        system_tokens, use_dummy_thought,
        state
    );

    // Cleanup
    llama_free(ctx);
    llama_model_free(model);
    llama_backend_free();
    return 0;
}
