#include "session_utils.h"
#include "common.h"
#include "token_generator.h"
#include "output.h"
#include "tokens.h"
#include "network.h"  // For LIM_LOG_DIR
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>

using namespace std;

// Forward declarations
extern bool is_debug;
extern std::ofstream chat_log;
extern std::ofstream token_log;
extern std::ofstream tps_log;
extern bool honest_speed;

vector<llama_token> build_user_assistant_turn(llama_context* ctx, const string& input);

std::string html_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '&') out += "&amp;";
        else if (c == '<') out += "&lt;";
        else if (c == '>') out += "&gt;";
        else if (c == '"') out += "&quot;";
        else out += c;
    }
    return out;
}

std::string html_escape_for_browser(const std::string& s) {
    std::string escaped = html_escape(s);
    size_t pos = 0;
    while ((pos = escaped.find('\n', pos)) != std::string::npos) {
        escaped.replace(pos, 1, "<br>");
        pos += 3;
    }
    return escaped;
}
bool open_session_logs(int idx) {
    string log_file_name = LIM_LOG_DIR + "/" + to_string(idx);
    chat_log.open(log_file_name, ios::app);
    if (!chat_log.is_open()) return false;

    if (is_debug) {
        string token_log_name = LIM_LOG_DIR + "/" + to_string(idx) + ".tokens";
        token_log.open(token_log_name, ios::trunc);
        if (token_log.is_open()) {
            token_log << "# Token Log - Session #" << idx << "\n";
            token_log << "# Format: FEED <label> <token_id> \"<escaped_piece>\"   (tokens fed into context)\n";
            token_log << "#         <seq> <token_id> \"<escaped_piece>\"                     (tokens generated by LLM)\n";
            token_log << "# Escaping: \\n = newline, \\r = carriage return, \\t = tab\n";
        }
    }

    string tps_log_name = LIM_LOG_DIR + "/" + to_string(idx) + ".tps";
    tps_log.open(tps_log_name, ios::trunc);
    if (tps_log.is_open()) {
        tps_log << "# TPS Log - Session #" << idx << "\n";
    }
    return true;
}

void log_tokens(const std::string& label, const std::vector<llama_token>& toks, llama_context* ctx) {
    if (!is_debug || !token_log.is_open()) return;
    for (llama_token t : toks) {
        std::string piece = common_token_to_piece(ctx, t);
        token_log << label << " " << t << " \"" << escape_token_piece(piece) << "\"\n";
    }
    token_log.flush();
}

void strip_tags(std::string& str, const std::vector<std::string>& tags) {
    for (const auto& tag : tags) {
        size_t p;
        while ((p = str.find(tag)) != string::npos) {
            str.erase(p, tag.length());
        }
    }
}

void diag_speed(int n_past, int n_ctx, int t_count, double elapsed, double decode_time) {
    if (t_count <= 0 || elapsed <= 0.0) return;
    double context_percent = (n_past / (double)n_ctx) * 100.0;

    // Pick denominator based on honest_speed global
    double denom = elapsed;  // default: wall clock ("honest")
    if (!honest_speed && decode_time > 0.0) {
        denom = decode_time;
    }

    double speed = t_count / denom;
    int speed_rounded = round_int(speed);

    // Write to TPS log file
    tps_log << n_past << " " << std::fixed << std::setprecision(3) << speed << "\n";

    // Send to browser status bar (compact: no labels)
    if (should_output_to_browser()) {
        std::ostringstream oss2;
        oss2 << speed_rounded << " t/s | " << n_past << " (" << (int)context_percent << "%)";
        stream_speed(oss2.str());
    }
}
void diag_restore(const std::string& path, int token_count) {
    diag("Restoring session from " + path + "... (" + std::to_string(token_count) + " tokens)", "\033[35m");
}

bool strip_checkpoints_flag(std::string& arg) {
    static const std::string flag = " --checkpoints";
    if (arg.size() >= flag.size() &&
        arg.compare(arg.size() - flag.size(), flag.size(), flag) == 0) {
        arg.erase(arg.size() - flag.size());
        return true;
    }
    return false;
}

void announce_new_session(int session_num) {
    diag("Session #" + std::to_string(session_num) + " started: type /help to see a list of commands", "\033[35m");
    if (chat_log.is_open()) {
        chat_log << "=== SYSTEM ===\nStarting LLM Controller Session (#" + std::to_string(session_num) + ")\n\n";
        chat_log.flush();
    }
}
std::string get_git_head_sha() {
    FILE* pipe = popen("git rev-parse HEAD 2>/dev/null", "r");
    if (!pipe) return "";
    char buf[48];
    std::string sha;
    if (fgets(buf, sizeof(buf), pipe)) {
        sha = buf;
        while (!sha.empty() && (sha.back() == '\n' || sha.back() == '\r')) sha.pop_back();
    }
    pclose(pipe);
    return sha;
}

// Check git HEAD against saved SHA. If mismatched, warns the user and
// injects a message into restored_tokens, decoding it into the KV cache so
// the model actually sees the note and the cache/token tracker stay in sync.
// Returns true if there was a mismatch.
bool check_git_head_on_restore(const std::string& save_path, const std::string& saved_sha,
                                llama_context* ctx, llama_batch& batch, int& n_past,
                                std::vector<llama_token>& restored_tokens, int n_batch) {
    if (saved_sha.empty()) return false;

    std::string current_sha = get_git_head_sha();
    if (current_sha.empty() || saved_sha == current_sha) return false;

    std::string short_saved = saved_sha.substr(0, 7);
    std::string short_current = current_sha.substr(0, 7);
    diag("Git HEAD mismatch: session was at " + short_saved + ", currently at " + short_current, "\033[33m");

    // Inform the LLM about code changes.
    auto git_msg = build_user_assistant_turn(ctx,
        "Note: Git HEAD has changed since this session was saved (was " + short_saved + ", now " + short_current + "). Code or configuration may have been modified.");

    // The note must fit in the remaining context (same >= convention as
    // feed_user_message): it is decoded into the KV cache and appended to the
    // token tracker, so both must stay consistent.
    if (n_past + (int)git_msg.size() >= (int)llama_n_ctx(ctx)) {
        diag("Git HEAD note skipped: no context room left", "\033[33m");
        return true;
    }

    // Decode the note so the model sees it (previously it was added to the
    // batch without a decode: the model never saw the note, the positions were
    // phantom KV slots, and the stale batch was silently dropped by the next
    // feed).
    int git_start = n_past;
    bool ok = true;
    for (int i = 0; i < (int)git_msg.size() && ok; i += n_batch) {
        int chunk = std::min(n_batch, (int)git_msg.size() - i);
        if (chunk <= 0) break;
        batch.n_tokens = 0;
        for (int j = 0; j < chunk; j++) {
            common_batch_add(batch, git_msg[i + j], n_past + j, {0}, (i + j == (int)git_msg.size() - 1));
        }
        n_past += chunk;
        if (llama_decode(ctx, batch) != 0) ok = false;
    }

    if (!ok) {
        // Defensive (the fit check above should make this unreachable): roll
        // the note out of the KV cache and leave the tracker untouched.
        llama_memory_seq_rm(llama_get_memory(ctx), 0, git_start, -1);
        n_past = git_start;
        diag("Git HEAD note failed to decode; skipped", "\033[33m");
        return true;
    }

    restored_tokens.insert(restored_tokens.end(), git_msg.begin(), git_msg.end());
    return true;
}

void diag_session_restored(int session_num, size_t n_tokens, int n_ctx, const std::string& git_short) {
    string msg = "Session #" + std::to_string(session_num) + " restored: " + std::to_string(n_tokens) + " tokens loaded " + context_pct(n_tokens, n_ctx);
    if (!git_short.empty()) msg += " (git: " + git_short + ")";
    diag(msg, "\033[32m");
}

